server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://sh-cdb-lf52oq0s.sql.tencentcdb.com:63734/
    username: root
    password: 34banNA$#
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 15
      minimum-idle: 5
      auto-commit: true
      h
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
mybatis:
  type-aliases-package: com.wf.projectboot.user.model
  mapper-locations: classpath:mybatis/mapper/*.xml



#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql